### PR TITLE
feat: basic editor pt.1

### PR DESCRIPTION
**Pull request by ashifolfi**
- Entity Select panel to select a scene or entity (minus the editor scene)
  - Can add/remove entities and scenes
- Inspector panel to edit properties of an entity or scene
  - Can add/remove components and edit their properties
- Change the editor root panel to be Controls panel, now holds controls for the editor scene and imguizmo
  - Add imguizmo to modify transform of a selected entity
  - Remove mesh conversion functionality
- Add external tooling cmake framework
  - Move mesh conversion code to external tool `cmdltool`
- Restructure cmake to split libraries / executables into subfiles
  - `ChiraEngine` -> `engine`
  - `ChiraEditor` -> `editor`

### CODE REVIEW

**Comment by ashifolfi** [comment]
I'm done dealing with codacy's bullshit. there is literally no other solution I know of to do what I'm trying to do. strncpy is going to be there. deal with it. I check the lengths and I know that getName will never be null without other errors getting in the way (no uuid would be the cause)

I'm ignoring that error.

**Comment by ashifolfi** [comment]
I have left the runner test disabled for now because it's untested and very scuffed (also only works on windows)

**Comment by ashifolfi** [comment]
a huge part of the editor involves the whole scene saving and loading which does also involve some rework in how the engine handles everything. My solution was to load games as dll files and use a runner to launch the engine ala source. the engine is it's own library separate from the runner

**Comment by ashifolfi** [comment]
I love how git refused to let me revert the commits properly that's so cool :+1:

**Review by craftablescience — APPROVED** [review]
based pr

**Pull request merged**
